//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRT_Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForecastPeriod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ForecastPeriod()
        {
            this.ForecastPeriodCompetitorValue = new HashSet<ForecastPeriodCompetitorValue>();
            this.ForecastPeriodResultRemark = new HashSet<ForecastPeriodResultRemark>();
            this.ForecastPeriodToolAndMethod = new HashSet<ForecastPeriodToolAndMethod>();
            this.ForecastValueAndRealValue = new HashSet<ForecastValueAndRealValue>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ImportantIndicatorResultMeasureID { get; set; }
        public string MountOrQuarterOrYear { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ForecastPeriodCompetitorValue> ForecastPeriodCompetitorValue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ForecastPeriodResultRemark> ForecastPeriodResultRemark { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ForecastPeriodToolAndMethod> ForecastPeriodToolAndMethod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ForecastValueAndRealValue> ForecastValueAndRealValue { get; set; }
        public virtual ImportantIndicatorResultMeasurement ImportantIndicatorResultMeasurement { get; set; }
    }
}
