//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRT_Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indicator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Indicator()
        {
            this.ImportantIndicatorResultMeasurement = new HashSet<ImportantIndicatorResultMeasurement>();
            this.ImportantIndicatorTargetMeasurement = new HashSet<ImportantIndicatorTargetMeasurement>();
            this.IndicatorOwner = new HashSet<IndicatorOwner>();
            this.IndicatorUnit = new HashSet<IndicatorUnit>();
            this.IndicatorXIndicatorType = new HashSet<IndicatorXIndicatorType>();
            this.PredicOwner = new HashSet<PredicOwner>();
        }
    
        public int ID { get; set; }
        public string Indicator1 { get; set; }
        public string Formula { get; set; }
        public Nullable<int> IndicatorDetailStatusID { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsLastDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImportantIndicatorResultMeasurement> ImportantIndicatorResultMeasurement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImportantIndicatorTargetMeasurement> ImportantIndicatorTargetMeasurement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndicatorOwner> IndicatorOwner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndicatorUnit> IndicatorUnit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndicatorXIndicatorType> IndicatorXIndicatorType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PredicOwner> PredicOwner { get; set; }
        public virtual IndicatorDetailStatus IndicatorDetailStatus { get; set; }
    }
}
