//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRT_Demo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MRTEntities : DbContext
    {
        public MRTEntities()
            : base("name=MRTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ForecastAnalysisResultFile> ForecastAnalysisResultFile { get; set; }
        public virtual DbSet<ForecastChangeActionPlanFile> ForecastChangeActionPlanFile { get; set; }
        public virtual DbSet<ForecastPeriod> ForecastPeriod { get; set; }
        public virtual DbSet<ForecastPeriodCompetitorValue> ForecastPeriodCompetitorValue { get; set; }
        public virtual DbSet<ForecastPeriodDocFile> ForecastPeriodDocFile { get; set; }
        public virtual DbSet<ForecastPeriodResultRemark> ForecastPeriodResultRemark { get; set; }
        public virtual DbSet<ForecastPeriodToolAndMethod> ForecastPeriodToolAndMethod { get; set; }
        public virtual DbSet<ForecastTool> ForecastTool { get; set; }
        public virtual DbSet<ForecastValueAndRealValue> ForecastValueAndRealValue { get; set; }
        public virtual DbSet<Goal> Goal { get; set; }
        public virtual DbSet<ImportantIndicatorResultMeasurement> ImportantIndicatorResultMeasurement { get; set; }
        public virtual DbSet<ImportantIndicatorTargetMeasurement> ImportantIndicatorTargetMeasurement { get; set; }
        public virtual DbSet<Indicator> Indicator { get; set; }
        public virtual DbSet<IndicatorDetailStatus> IndicatorDetailStatus { get; set; }
        public virtual DbSet<IndicatorOwner> IndicatorOwner { get; set; }
        public virtual DbSet<IndicatorType> IndicatorType { get; set; }
        public virtual DbSet<IndicatorUnit> IndicatorUnit { get; set; }
        public virtual DbSet<IndicatorXIndicatorType> IndicatorXIndicatorType { get; set; }
        public virtual DbSet<PeriodMountOrQuarterOrYear> PeriodMountOrQuarterOrYear { get; set; }
        public virtual DbSet<PredicOwner> PredicOwner { get; set; }
        public virtual DbSet<SOEPlan> SOEPlan { get; set; }
        public virtual DbSet<StrategicObjective> StrategicObjective { get; set; }
        public virtual DbSet<Strategy> Strategy { get; set; }
        public virtual DbSet<Tactic> Tactic { get; set; }
    }
}
